### ISSUE TITLE
DF Automation (Keep3r/Gelato) - Build verifiable reward calculation workflow

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#105]
The same computations that we’re doing now will need to be maintained, and we may want to consider using Keep3r, and similar products to complete this.

**Comment by trentmc** [comment]
Closing this, it's redundant with
https://app.zenhub.com/workspaces/ve--df-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-issues/114
