### ISSUE TITLE
OP Value Stream - Requirements & Design

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#106]
#### High Level Examples
_Source => Destination_
Ocean Fees => OPC
OPC => Distributor Router
Vesting Wallet => Distributor Router
Distributor Router => FeeDistributor < Passive Rewards
Distributor Router => DFRewards < Active Rewards
Distributor Router => DAOGrants/Algovera < Signed Grants/Rewards

This is just a loose list of value-flows that need to happen in order to stream funds across the protocol, automating parts of our treasury and our incentive programs.

### DoD:
- [ ] Requirements have been gathered (20%)
- [ ] Contracts, roles, interfaces, events, parameters have been well defined (80%)
- [ ] No development has begun

**Comment by idiom-bytes** [comment]
estimate(5) ~= 3 days

REF: Broad stroke diagram WIP.
Devil is in the details. Many contracts/flows/interfaces need to be better defined.
https://drive.google.com/file/d/1E6kuM_2-hX6rcN8rbuhgcxG1XIGo34Jt/view?usp=sharing

**Comment by trentmc** [comment]
Closing, this is redundant with https://app.zenhub.com/workspaces/ve--df-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-issues/114
