### ISSUE TITLE
staging nginx is not routing

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#113]
can't connect to apps via urls. docker services seem to be running in the right ports, and nginx seems to be running as 

i was testing and merging prs, and staging was having issues deploying more containers (too many services) and hung...
I had to stop and restart the vm.

i resumed the vm, and everything seemed to be there, as expected. The docker containers seem to be running, However, I have not be able to resolve the url => app via nginx.

I'm sharing sad times here in anticipation of asking for help :disappointed: 

example: test-df.oceandao.org

**Comment by KatunaNorbert** [comment]
Fixed
