### ISSUE TITLE
Ocean marketplace is reporting volatile metrics, that may not be representative of what they want to show 

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#115]
Problem:
- Right now numbers being reported in marketplace are not 1:1 w/ data explorer
- dfsql route offers metrics that have been calculated based on the epoch
- marketplace should be consuming from dfsql to report epoch-adjusted metrics
- marketplace may want to continue consuming from dfsql so numbers reported are 1:1 between products

You can see the discussion on slack here:
https://oceanprotocol.slack.com/archives/C026BNFH6HK/p1667411937633519?thread_ts=1667407271.254359&cid=C026BNFH6HK

What dfsql reports: 188k (correct amount)
![Screenshot 2022-11-02 at 18.37.54.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/e419bfe5-93ea-422f-931d-c4ab92114b3c)

What marketplace is reporting: varying values, that do not map to the calculations from dfsql
![Screenshot 2022-11-02 at 18.33.58.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/02a80e52-8f06-4cb9-bcf3-553b6ec2e148)
![Screenshot 2022-11-02 at 18.20.10.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/89754518-80ad-4dfe-80d8-63011da0d8a5)

### DoD:
- [ ] Marketplace is reporting accurate numbers relative to what they are trying to show to users
- [ ] Wherever applicable, marketplace and df portal should be reporting 1:1 metrics as marketplace should be consuming from dfsql rather than computing it's own metrics within the marketplace app

**Comment by idiom-bytes** [comment]
There should be no difference between the marketplace and dfsql, they are pulling directly from it.

https://oceanprotocol.slack.com/archives/CNDG1849Z/p1667462170441379?thread_ts=1667437114.240239&cid=CNDG1849Z

**Comment by idiom-bytes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-issues/115?planning-poker) with Zenhub @KatunaNorbert

**Comment by trentmc** [comment]
old. closing
