### ISSUE TITLE
Abstract DF-RF from DF-PY

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#137]
### Problem:
For builders, there are many dependencies currently in the way to execute the Reward Function (RF). This also blocks us from simulating, and iterating around the RF.

So, if we're iterating on wash consume, or mechanisms around building value flows, then participants would benefit from having rewards estimated in order to see if their data strategy is working as expected.

Because of dependencies on df-py and other repositories (dfsql) it will be easier to split this off into it's own repo. By having a dedicated repo for this, users can calculate their rewards and estimate DF yields from their strategy.

As a Builder: It would be great to easily run this, and estimate how my farm, dao, or system behaves in a simulation/test environment.
As an App: It would be great to easily run this, and estimate how DF will perform this week and build my own analysis on top of what's happening live.

### DoD:
- [ ] remove df-rf from df-py as to make it incredibly easy to import and use in an isolated environment
- [ ] Users can easily grab df-rewardcalc and get an estimate for their strategy/value-flow

**Comment by trentmc** [comment]
This is duplicate with https://github.com/oceanprotocol/df-py/issues/382.

FYI it's not big enough to be an epic. It's probably 1-2 days of work.

Closing.

**Comment by idiom-bytes** [comment]
Removing from roadmap...
