### ISSUE TITLE
Complete PRs from market

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#138]
### Problem
ICs are still contributing.
Set estimate for total time together.

### DoD:
- Under review:
- [ ] https://github.com/oceanprotocol/market/pull/1674

- [ ] https://github.com/oceanprotocol/market/pull/1794
--- This PR covers the following issues, and has been reviewed and approved. ---
https://github.com/oceanprotocol/market/issues/1724
https://github.com/oceanprotocol/market/issues/1554
https://github.com/oceanprotocol/market/issues/1844

- This barge PR needs to be tested on Ubuntu:
- [ ] https://github.com/oceanprotocol/market/pull/1729

**Comment by EnzoVezzaro** [comment]
all PRs are under review

**Comment by idiom-bytes** [comment]
@bogdanfazakas @AnaLoznianu we believe these issues are pretty heavily reviewed and are just awaiting to be merged. I'm pinging you both for support on the marketplace so we can merge & close these tasks.

Thank you!!
