### ISSUE TITLE
Complete PRs from market

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#139]
# DoD:
- [ ] The following PRs have been reviewed, tested, and closed.
- https://github.com/oceanprotocol/market/pull/1865
- https://github.com/oceanprotocol/market/pull/1795
- https://github.com/oceanprotocol/market/pull/1774

**Comment by jamiehewitt15** [comment]
All three are currently in review

**Comment by idiom-bytes** [comment]
Most of this is now fairly approved, reviewed, and ready to go.
@kremalicious @mihaisc ball is in your court
