### ISSUE TITLE
Onboard on DF stack

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#141]
1. Get df-py setup and running
https://github.com/oceanprotocol/df-py

2. Deploy web-app
https://github.com/oceanprotocol/df-web

3. Familiarize yourself with (2) from 404 and provide some feedback, run tests, help get across finish line
https://github.com/oceanprotocol/df-py/pull/404

To Add:
- Data flow docs
- Recommended reading: df-py, df-sql df-web readmes

**Comment by jamiehewitt15** [comment]
When you say "Deploy web-app" do you mean run it locally? Or familiarise myself with the deployment process?

**Comment by KatunaNorbert** [comment]
I think he meant running it locally, the deployment process it's similar with the one from the marketplace

**Comment by idiom-bytes** [comment]
Sharing the "knowledge arc".
It's a journey, not a race...

1. Yup, deploy it locally however you can.
Get familiar with developing on top of ganache and pointing towards other data sources/services (i.e. mainnet subgraph/eth) to manage your environment.

2. Then I'm going to challenge you guys to get more local.
Do it via barge w/ df-py running locally, with your own local df-sql and subgraph.
And run the python pipeline to iterate on the df-py reward-formula w/ query and everything else.

3. We also manage this in the VMs.
I.E. Updating df-sql in production vm

4. We currently do not have a container management system like ECS to scale this out effectively
It's all manual deployments on the VM

No bueno. But great so far, it has led us to here!
Let's keep learning and improving the system.
