### ISSUE TITLE
Prepare to launch (3) - Publisher Rewards - Phase 2

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#144]
### Problem
Publisher will receive 2x Multiplier as part of the first release, but that's not the target.
We need to move towards the second release.

##### Second Release
We're going to take the 2x reward, and split the stream into it's own reward stream
Publisher Rewards will become a separate calc/data flow stream
Publisher Rewards will become a separate dispense event
Publisher Rewards will have their own df-sql API and other data sources
Publisher Rewards will have their own FE components and description

**Comment by trentmc** [comment]
Given Predictoor, DF Challenge, DF Predictoor: this is super-low priority, and will look different when revisited. And we have _way_ too many issues. So closing this.
