### ISSUE TITLE
Move config from epoch.json upstream so we reduce the # of places to configure epochs

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#145]
Updates to epochs.json => moving it upstream so all configs are in 1 place
----------------------
- df-py is going to read the veFeeDistributor
- when df-py when calculating rewards, needs a root number

3 tables in df-sql
 	- passive rewards
	- curator rewards
	- [redacted] rewards

Now I can code whatever I want in df-web
- if I want to change the amount is at least connected
- we're going to move it into 1 place

Forward looking
------------------------------
- We need to address different amounts between reward types

amt_of_tokens => needs to become 3 different streams
1. amt_of_tokens_passive
1. amt_of_tokens_curator
1. amt_of_tokens_[redacted]

Please expand on the details of
------------------------------
- Where this will be configured
- How this will be sent downstream to df-sql
- How df-sql will serve this

**Proposal for easy-to-digest => round_config_table**
- passive_available
- passive_distributed
- curator_available
- curator_distributed
- [redacted]_available
- [redacted]_distributed

**Comment by idiom-bytes** [comment]
At the end of the meeting we had proposed CandB: Which is to not delete epoch,json, and simply reference it wherever needed.

**Comment by trentmc** [comment]
@idiom-bytes 
- is this issue still even relevant? Of any real priority?
- if yes, it's hard to understand. Eg for starters I have no idea where epochs.json is. So please revise the title & description so that it provides more context.
