### ISSUE TITLE
Blogpost for completing DF25 and launching 26

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#146]
Blog post + twitter thread goes out every Wednesday @ 23:59 GMT

**Comment by nickscavuzzo33** [comment]
@idiom-bytes framing the blog post to be launched tomorrow here https://docs.google.com/document/d/1KO4-kwxT4k3A-cCfOACx0FeQT9PZl7gnsYyA1HCxHxc/edit?usp=sharing pleae add feedback

**Comment by idiom-bytes** [comment]
Thank you ser!
