### ISSUE TITLE
In docs, explain APYs for DF/VE

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-issues#157]
We don't have a place where we explain how we calculate the APY for a user.
Proposed solution:
Inside the Rewards section of our documentation explain how the total APY it's calculated for a user and for each type of rewards(active/passive) explain the APY calculation formula.
We iterated on this previously and we have most of the data written inside this [document](https://docs.google.com/document/d/1Y-1Mmmu49VZ7zZ7RnsCDfwj22dQK15lmyQFTG0QE2KA/edit#heading=h.3jjeezubomjz), let's also get this information inside our documentation and make it available for everyone.

**Comment by trentmc** [comment]
Given Predictoor, DF Challenge, DF Predictoor: this is super-low priority, and will look different when revisited. And we have _way_ too many issues. So closing this.
