### ISSUE TITLE
Create Public dashboard for TVL, DCV, more over time

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-issues#78]
**Key plots:**
- TVL,vs time
- DCV, vs time
- \# datasets, vs time
- \# consumes, vs time
- \# LPs, vs time
- DF Rewards dispensed, vs time (weekly)

**Secondary plots:**
- TVL % daily growth, vs time
- DCV % ""
- \# datasets % ""
- \# consumes % ""
- \# LPs vs time % ""

**Other refs:**
- Roberto's 1yo Dune dashboards: [1](https://dune.com/idiom/tttt), [2](https://dune.com/idiom/test_ocean_tvl)
- [Old Gdoc for ref](https://docs.google.com/document/d/1JvnT7cMk3N4l1XiDh_0MpMNp2dVxM--pX-Qhg_XFDRc/edit#)
- profile metric: sales revenue [market#871](https://github.com/oceanprotocol/market/issues/871)
- Track total data $ volume consumed / day, and total data $ volume bought / day: [market#380](https://github.com/oceanprotocol/market/issues/380)

**Prototype:**

Interactivity works similarly to Coingecko [example](https://www.coingecko.com/en/coins/bitcoin).

![unnamed](https://user-images.githubusercontent.com/5305452/176909924-3026fd5f-465f-4332-bb82-3e08e9272a10.jpg)

**Comment by idiom-bytes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-issues/78?planning-poker) with Zenhub @KatunaNorbert

**Comment by idiom-bytes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-issues/78?planning-poker) with Zenhub @trizin

**Comment by trentmc** [comment]
Between autobots and ocean stats, this is done
