### ISSUE TITLE
Prep for "DFx dispense", by going through ops page

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#79]
**Background**

Rewards distribution ops page:
https://github.com/oceanprotocol/df-py/blob/main/README-dist-ops.md

Related issues: DF3 dispense, DF4 dispense, ..

Trent is doing rewards distribution until Aug. (With Berkay and Norbert help when issues.) He's assigned the related DFX issues: DF3, DF4, DF5 dispense.

Trent's away in Aug. The week before is DF6 dispense. Roberto will this one, with Trent helping as needed.

When Trent's away, Roberto will do dispensing: DF7, DF8, DF9, DF10 dispense.

When Trent's back, Trent will do this again. The first week, with Roberto's help (DF11).

**TODO**

Aim of _this_ issue: Roberto prep for rewards distribution in Aug

- [ ] In mid-July (not sooner), Roberto go through the rewards distribution ops page end-to-end. Don't do sooner because it could evolve a lot.

That's all for this ticket! The rest is covered by DFX rewards distributions tickets.

**Comment by idiom-bytes** [comment]
We are working towards automating this.
I'm happy to provide support, however this seems dated and propose we close it.

**Comment by trentmc** [comment]
Done and/or obsolete. Closing
