### ISSUE TITLE
`deposit_for` only works if the address has an active veOCEAN lock

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-issues#83]
`deposit_for` function only works if the address has an active veOCEAN lock. We can't lock on the user's behalf because lock duration varies.

Possible solutions if the lock is expired:
- Ask the user to create a lock before calling the claim function.
- use OCEAN

**Comment by idiom-bytes** [comment]
In order to maintain functionality and support auto-lock, candidate (1) is a good solution.
How to address:
- Create a pop-up if the user doesn't have a lock
- "You must have a lock in place, you can use as little as 0.1 OCEAN"
- User creates lock, and can claim amount
